#+title: redis 持久化配置
#+STARTUP: overview indent
#+HTML_HEAD: <link href="../java/style.css" rel="stylesheet" type="text/css" />
#+LANGUAGE: zh-CN

- RDB持久化
  - RDB持久化：默认开启；全量备份，一次性保存整个数据库；体积小，数据恢复快；服务器异常时可能会丢失部分数据；SAVE操作会阻塞，BGSAVE不阻塞
  - Redis数据持久化是将内存中的数据保存到磁盘里，避免数据意外丢失。RDB持久化会生成一个RDB文件，这个RDB文件是一个经过压缩的二进制文件。通过该文件可以还原出Redis数据库中的数据。RDB的持久化可以手动执行，也可以根据服务器配置项定期自动执行。

  - 有两个命令可以创建RDB文件，一个是SAVE同步，另一个是BGSAVE异步
  - RDB文件的载入工作是在服务器启动时自动执行的，只要Redis服务器在启动时检测到RDB文件存在，就会自动载入RDB文件。值得一提的是，Redis服务器在载入RDB文件的期间，会一直处于阻塞状态，直到载入工作完成为止。

  - BGSAVE命令在不阻塞服务器进程的情况下执行，所以Redis允许用户通过设置服务器的save选项来让服务器每隔一段时间自动执行一次BGSAVE命令。

    #+BEGIN_SRC redis
    save 900 1
    save 300 10
    save 60  10000
    #+END_SRC

    上面条件只要满足其中一个，BGSAVE命令就会被执行：

    第一条的意思是：服务器在900秒内对数据库执行过至少1次修改，就会执行BGSAVE命令
    第二条的意思是：服务器在300秒内对数据库执行过至少10次修改，就会执行BGSAVE命令
    第三条的意思是：服务器在60秒内对数据库执行过至少10000次修改，就会执行BGSAVE命令
- AOF
  - AOF持久化：默认关闭；增量备份，一次保存一个修改数据库的命令；体积大，数据恢复慢；备份频率可以自己设置；不会出现阻塞
  - always表示每次执行写入操作，就会立即将内存缓冲区中的内容同步到磁盘中的AOF文件中。这种配置性能比较差，但是可以确保数据不丢失。
  - everysec表示每秒执行一次将操作系统的内存缓冲区中的数据同步到磁盘的AOF文件中，这个操作由一个线程来负责，性能很高。
  - no表示由操作系统来控制何时将内存缓冲区中的数据同步到硬盘的AOF文件中。这种操作在服务器出现异常时会丢失一部分数据。
